---
title: Prior To Box
output: 
  html_document:
    number_section: false 
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
<!-- this makes the page wider --> 
<style type="text/css">
.main-container {
  max-width: 1200px !important;
  margin-left: auto;
  margin-right: auto;
}
</style>


```{r loadpackages, warning = FALSE, message = FALSE}
#load packages 
library(ggplot2)
library(dplyr)
library(glue) 
library(cowplot)
knitr::opts_chunk$set(fig.width = 12, fig.height = 12)
```

**Goal:** 

A. Frequency of cars by `manufacturer`, `cyl`, `drv` and `class`   
B. Slope plot of average of `cty` for years 1999 and 2008 by `manufacturer`, `cyl`, `drv` and `class` 

# {.tabset}

## Option 1

### Write Out Code  


```{r option0}
# A PLOTS 

optA1<- mpg %>% 
  count(manufacturer) %>%
  mutate(ordered = reorder(manufacturer, n)) %>% 
  arrange(ordered) %>% 
ggplot(., aes(x = n, y = ordered)) + 
  geom_col() + 
  labs( 
      title = "Frequency of Manufacturer"
    , subtitle = "mpg data set"
    , y     = "Manufacturer"
    , x     = "Count"
  )

optA2 <- mpg %>% 
  count(cyl) %>%
  mutate(ordered = reorder(cyl, n)) %>% 
  arrange(ordered) %>% 
ggplot(., aes(x = n, y = ordered)) + 
  geom_col() + 
  labs( 
      title = "Frequency of Number of Cylinders"
    , subtitle = "mpg data set"
    , y     = "Number of Cylinders"
    , x     = "Count"
  )

optA3 <- mpg %>% 
  count(drv) %>%
  mutate(ordered = reorder(drv, n)) %>% 
  arrange(ordered) %>% 
ggplot(., aes(x = n, y = ordered)) + 
  geom_col() + 
  labs( 
      title = "Frequency of Drive Type"
    , subtitle = "mpg data set"
    , y     = "Drive Type"
    , x     = "Count"
  )

optA4 <- mpg %>% 
  count(class) %>%
  mutate(ordered = reorder(class, n)) %>% 
  arrange(ordered) %>% 
ggplot(., aes(x = n, y = ordered)) + 
  geom_col() + 
  labs( 
      title = "Frequency of Class"
    , subtitle = "mpg data set"
    , y     = "Class"
    , x     = "Count"
  )


# B PLOTS 

optB1<-mpg %>% 
  group_by(year, manufacturer) %>% 
  summarize(mean = mean(cty), .groups = "keep") %>%  
ggplot(., aes(x = year, y = mean, color = manufacturer)) + 
  geom_line() +
  geom_point() + 
  scale_x_continuous(breaks = c(1999,2008)) + 
  scale_color_discrete(name = "Manufacturer") + 
  labs( 
      title = "Average City MPG by Year and Manufacturer"
    , y     = "Average of City Miles per Gallon"
    , x     = "Year"
  )

optB2<-  mpg %>% 
  group_by(year, cyl) %>%
  summarize(mean = mean(cty), .groups = "keep") %>%  
ggplot(., aes(x = year, y = mean, color = as.character(cyl))) + #make cyl character for discrete legend!
  geom_line() +
  geom_point() + 
  scale_x_continuous(breaks = c(1999,2008)) + 
  scale_color_discrete(name = "Number of Cylinders") + 
  labs( 
      title = "Average City MPG by Year and Number of Cylinders"
    , y     = "Average of City Miles per Gallon"
    , x     = "Year"
  )

optB3<-mpg %>% 
  group_by(year, drv) %>% 
  summarize(mean = mean(cty), .groups = "keep") %>%  
ggplot(., aes(x = year, y = mean, color = drv)) + 
  geom_line() +
  geom_point() + 
  scale_x_continuous(breaks = c(1999,2008)) + 
  scale_color_discrete(name = "Drive Type") + 
  labs( 
      title = "Average City MPG by Year and Drive Type"
    , y     = "Average of City Miles per Gallon"
    , x     = "Year"
  )

optB4<-mpg %>% 
  group_by(year, class) %>% 
  summarize(mean = mean(cty), .groups = "keep") %>%  
ggplot(., aes(x = year, y = mean, color = class)) + 
  geom_line() +
  geom_point() + 
  scale_x_continuous(breaks = c(1999,2008)) + 
  scale_color_discrete(name = "Class") + 
  labs( 
      title = "Average City MPG by Year and Class"
    , y     = "Average of City Miles per Gallon"
    , x     = "Year"
  )

plot_grid(optA1, optA2, optA3, optA4, optB1, optB2, optB3, optB4, align = "hv", axis = "tblr", ncol = 2)

```


## Option 2

### Multiple Functions 


```{r option1}
# VAR NAMES DATA SET 
varnames <- tribble(
  ~var, ~name
  , "manufacturer", "Manufacturer"
  , "cyl"         , "Number of Cylinders"
  , "drv"         , "Drive Type"
  , "class"       , "Class"
)


## A Functions 

data_A <- function(VARst, DF = mpg, VARDF = varnames){
  
  VARname <- pull(filter(VARDF, var == all_of(VARst)), name)
  
  toPlot <- DF %>%
    rename(VAR = all_of(VARst)) %>% #set comment name for specific row 
    count(VAR) %>%
    mutate(VAR = reorder(VAR, n)) %>%
    arrange(VAR)
  
  OUT <- list(var = VARst, df = toPlot, name = VARname)
  return(OUT)
}

plot_A <- function(LIST){
  OUT <- LIST$df %>% 
  ggplot(., aes(x = n, y = VAR)) + 
  geom_col() + 
  labs( 
      title = glue("Frequency of {LIST$name}")
    , subtitle = "mpg data set"
    , y     = glue("{LIST$name}")
    , x     = "Count"
  )
  return(OUT)
}


## B Functions 

data_B <- function(VARst, DF = mpg, VARDF = varnames){
  
  VARname <- pull(filter(VARDF, var == all_of(VARst)), name)
  
  toPlot <- DF %>%
    rename(VAR = all_of(VARst)) %>% #set comment name for specific row 
    group_by(year, VAR) %>% 
    summarize(mean = mean(cty), .groups = "keep")
  
  OUT <- list(var = VARst, df = toPlot, name = VARname)
  return(OUT)
}

plot_B <- function(LIST){
  OUT <- LIST$df %>% 
    ggplot(., aes(x = year, y = mean, color = as.character(VAR))) + 
    geom_line() +
    geom_point() + 
    scale_x_continuous(breaks = c(1999,2008)) + 
    scale_color_discrete(name = glue("{LIST$name}")) + 
     labs( 
        title = glue("Average City MPG by Year and {LIST$name}")
      , y     = "Average of City Miles per Gallon"
      , x     = "Year"
    )
  return(OUT)
}


plot_grid(
    plot_A(data_A("manufacturer"))
  , plot_A(data_A("cyl"))
  , plot_A(data_A("drv"))
  , plot_A(data_A("class"))
  , plot_B(data_B("manufacturer"))
  , plot_B(data_B("cyl"))
  , plot_B(data_B("drv"))
  , plot_B(data_B("class"))
  , align = "hv", axis = "tblr", ncol = 2
)

```


## Option 3

### One Long Function


```{r option2}

myfunc_AB <- function(VARst, PLOTOPT, DF = mpg){
  
  if (!toupper(PLOTOPT) %in% c("A", "B") ){
    warning("INCORRECT PLOT OPTION, MUST BE A (FREQUENCY ) OR B (CTY MPG AVERAGE BY YEAR)")
  } #check out the {typed} package for how to restrict input types and values https://github.com/moodymudskipper/typed
  
    VARDF <- tribble(
      ~var, ~name
      , "manufacturer", "Manufacturer"
      , "cyl"         , "Number of Cylinders"
      , "drv"         , "Drive Type"
      , "class"       , "Class"
    )
  
  VARname <- pull(filter(VARDF, var == all_of(VARst)), name)
  
  if (toupper(PLOTOPT) == "A"){
  
    OUT <-DF %>%
      rename(VAR = all_of(VARst)) %>% 
      count(VAR) %>%
      mutate(VAR = reorder(VAR, n)) %>%
      arrange(VAR) %>% 
    ggplot(., aes(x = n, y = VAR)) + 
      geom_col() + 
      labs( 
          title = glue("Frequency of {VARname}")
        , subtitle = "mpg data set"
        , y     = glue("{VARname}")
        , x     = "Count"
      )
  
  } else if (toupper(PLOTOPT) == "B"){
  
    OUT <- DF %>%
      rename(VAR = all_of(VARst)) %>% 
      group_by(year, VAR) %>% 
      summarize(mean = mean(cty), .groups = "keep") %>% 
    ggplot(., aes(x = year, y = mean, color = as.character(VAR))) + 
      geom_line() +
      geom_point() + 
      scale_x_continuous(breaks = c(1999,2008)) + 
      scale_color_discrete(name = glue("{VARname}")) + 
       labs( 
          title = glue("Average City MPG by Year and {VARname}")
        , y     = "Average of City Miles per Gallon"
        , x     = "Year"
      )
  
  } 
  
  return(OUT)
} #END myfunc_AB


VARst <- "manufacturer"
PLOTOPT <- "A"




plot_grid(
    myfunc_AB("manufacturer", "A")
  , myfunc_AB("cyl"         , "A")
  , myfunc_AB("drv"         , "A")
  , myfunc_AB("class"       , "A")
  , myfunc_AB("manufacturer", "B")
  , myfunc_AB("cyl"         , "B")
  , myfunc_AB("drv"         , "B")
  , myfunc_AB("class"       , "B")
  , align = "hv", axis = "tblr", ncol = 2
)

```

